name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Number generated entries / 10
        # Otherwise it is impossible to execute it on GHA runner
        run: |
          sed -i.bak -E 's/(: +[1-9](0|_)+)0/\1/g' \
            config_generation_from_scratch.tdk.yaml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest-testinfra yamllint

      - name: Verify yamls
        run: |
          yamllint -sd relaxed .

      - name: Build docker-compose
        run: |
          docker-compose pull
          docker-compose build

      - name: Run the workflow
        run: |
          docker-compose run tdk

      - name: Verify results
        run: py.test -v test_tdk.py
